# Create the kafka cluster.
version: "3"
services:
  zoo1:
      image: zookeeper
      restart: always
      hostname: zoo1
      ports:
        - 2181:2181
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost  # Cloud ip here should update
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092  # Cloud ip here should update
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock